<?php

/**
 *
 * @category  Sabbir
 * @package   Walcart_Otplogin
 * @author    Sabbir Hossain
 */

?>
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script>
    function clickCounter() {

    if (typeof(Storage) !== "undefined") {
        if (localStorage.clickcount) {
            if (Number(localStorage.clickcount) < 1) {
               $(".delay").attr("disabled","disabled");
               $('.resendotp').css('display', 'none')
               document.getElementById("result").innerHTML = "Please try again 30min later";
                var countdown = 1 * 60 * 1000;
                var timerId = setInterval(function(){
                  countdown -= 1000;
                  var min = Math.floor(countdown / (60 * 1000));
                  var sec = Math.floor((countdown - (min * 60 * 1000)) / 1000);
                  if (countdown <= 0) {
                     $(".delay").removeAttr("disabled");
                     $('.resendotp').css('display', 'block')
                     document.getElementById("result").innerHTML = "";
                     localStorage.clickcount = 2;
                     
                     clearInterval(timerId);
                  } else {
                     $("#countTime").html(min + " : " + sec);
                  }
                
                }, 1000);
                return;
            }
            localStorage.clickcount = Number(localStorage.clickcount) - 1
        } else {
            localStorage.clickcount = 1;
        }
        //document.getElementById("result").innerHTML = "You have 3 tries";
    } else {
        document.getElementById("result").innerHTML = "Sorry, your browser does not support web storage...";
    }
}
</script>
<div id="customer-popup-otp" class="customer-popup-otp">
    <div class="col-md-12">
        <div class="otpmessages"></div>
        <form class="form" method="post" id="form-otpsend" data-mage-init='{"validation":{}}'>
            <input type="hidden" name="redirect_url" value="<?php echo $this->getUrl('/'); ?>" />
            <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <div class="field otp required">
                    <div class="control">
                        <input type="password" placeholder="Enter OTP" name="otp" alt="otp" id="otp" class="input-text" data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="button" onclick="clickCounter()" class="action submit sendotpsubmit delay primary"><span><?= $block->escapeHtml(__('Enter OTP')) ?></span></button>
                </div>
                <h1 id="countTime"></h1>
                <span id="result"></span>
                <div class="secondary">
                    <a name="email" class="resendotp"><span><?= $block->escapeHtml(__('Resend OTP')) ?></span></a>
                </div>
               </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    require(["jquery"], function($) {
        $('.sendotpsubmit').on('click', function() {
            if ($('#form-otpsend').valid()) {
                $('body').loader().loader('show');
                $.ajax({
                    url: "<?php echo $block->getUrl('otplogin/account/otppost') ?>",
                    data: $('#form-otpsend').serialize(),
                    type: 'POST',
                    dataType: 'json',
                    success: function(response) {
                        $('body').loader().loader('hide');
                        if (response.errors) {
                            $(".message").remove();
                            $('<div class="message message-error error"><div>' + response.message + '</div></div>').appendTo('.otpmessages');
                        } else {
                            $(".message").remove();
                            $('<div class="message message-success success"><div>' + response.message + '</div></div>').appendTo('.otpmessages');
                            var url = $('#form-otpsend').find('input[name="redirect_url"]').val();
                            window.location.href = url;
                        }
                    },
                    error: function() {
                        $('body').loader().loader('hide');
                        $(".message").remove();
                        $('<div class="message message-error error"><div>An error occurred, please try again later.</div></div>').appendTo('.otpmessages');
                    }
                });
            }
        });



        $('.resendotp').on('click', function() {
            var customurl = "<?php echo $block->getUrl('otplogin/account/resendotp') ?>";
            $('body').loader().loader('show');
            $.ajax({
                url: customurl,
                type: 'POST',
                dataType: 'json',
                success: function(response) {
                    $(".message").remove();
                    $('body').loader().loader('hide');
                    $('<div class="message message-success success"><div>' + response.message + '</div></div>').appendTo('.otpmessages');
                },
                error: function() {
                    $('body').loader().loader('hide');
                    $(".message").remove();
                    $('<div class="message message-error error"><div>An error occurred, please try again later.</div></div>').appendTo('.otpmessages');
                }
            });
        });
    });
</script>
<script type="text/x-magento-init">
    {
                "#customer-popup-otp": {
                    "Walcart_Otplogin/js/action/customer-authentication-popup": {
                        "popupTitle": "<?php /* @escapeNotVerified */ echo __('Create an Account'); ?>",
                        "innerWidth": "600"
                    }
                }
            }
        </script>
</div>
